version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: f_db
    restart: always
    env_file:
     - .env
    ports:
     - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend

  migrate:
    image: migrate/migrate
    depends_on: 
      - database
    volumes:
      - /Users/nathan/code/foundant/migrations:/migrations
    command: ["-path", "/migrations/", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable", "up"]
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-vue
    ports:
     - "8080:8080"
    environment:
     - CHOKIDAR_USEPOLLING=true
    restart: always
    links:
     - backend
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile-go
    env_file: .env
    restart: always
    networks:
      - backend
    links:
        - database
    ports:
    - "4000:4000"
volumes:
  data:
networks:
    backend:
        driver: "bridge"


